smoother_server:
  ros__parameters:
    use_sim_time: true
    costmap_topic: global_costmap/costmap_raw
    footprint_topic: global_costmap/published_footprint
    robot_base_frame: base_link
    transform_timeout: 0.1
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "test_smoother_plugin::TestSmoother"
      cost_limit: 20

      # max_radius: 0.5          # Maximum curve setback distance in meters
      # curve_resolution: 8      # Number of sample points per Bézier curve

      chaikin_iterations: 3
      target_spacing: 0.05        # Waypoint spacing in meters
      min_segment_dist: 0.10      # Minimum edge length required for Chaikin cuts